import java.awt.Color;
import java.awt.GraphicsEnvironment;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.BevelBorder;
import javax.swing.border.Border;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on 27/05/2011, 08:29:44
 */

/**
 *
 * @author lcc
 */
public class Main extends javax.swing.JFrame {

    private boolean bordaAlterada;
    private Border original;
    private final static Border bordaVermelha = BorderFactory.createBevelBorder(BevelBorder.LOWERED, Color.RED, Color.RED);
    
    /** Creates new form Main */
    public Main() {
        bordaAlterada = false;
        int screenWidth = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDisplayMode().getWidth();
        int screenHeight = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDisplayMode().getHeight();
        initComponents();
        original = campoNumero.getBorder();
        setLocation((screenWidth - getWidth()) / 2, (screenHeight - getHeight()) / 2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        campoBinC2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoBits = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoNumero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoBin = new javax.swing.JTextField();
        labelOverflow = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        campoBin2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoDec2 = new javax.swing.JTextField();
        labelBintoDec = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Complementador a 2");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Decimal para binário"));

        campoBinC2.setEditable(false);
        campoBinC2.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel3.setText("Binário negativo");

        campoBits.setText("0");
        campoBits.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoBitsKeyReleased(evt);
            }
        });

        jLabel4.setText("Número de bits (0 para mínimo possível)");

        campoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                converter(evt);
            }
        });
        campoNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoNumeroKeyReleased(evt);
            }
        });

        jLabel1.setText("Decimal");

        jLabel2.setText("Binario positivo");

        campoBin.setEditable(false);
        campoBin.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        labelOverflow.setText("Status: sem overflow!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(campoBin, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(campoNumero))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(campoBits, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campoBinC2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(labelOverflow, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoBits, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoBinC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoBin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelOverflow, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Binário para decimal"));

        campoBin2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoBin2KeyReleased(evt);
            }
        });

        jLabel5.setText("Binário");

        jLabel6.setText("Decimal");

        campoDec2.setEditable(false);
        campoDec2.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelBintoDec, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(campoBin2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(campoDec2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoBin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoDec2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(labelBintoDec, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
        );

        jToggleButton1.setText("Sobre");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirCreditos(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jToggleButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static String complementa(String n){
        String resp = "";
        boolean achou1 = false;
        for(int i = n.length() - 1; i >= 0; i--){
            char atual = n.charAt(i);
            if(!achou1)
                resp = atual + resp;
            else
                resp = (atual == '1' ? '0' : '1') + resp;
            achou1 = achou1 || atual == '1';
        }
        return resp;
    }

    private void converter(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_converter
        try{
            int n = Integer.parseInt(campoNumero.getText());
            int bits = Integer.parseInt(campoBits.getText());
            String bin = '0' + Integer.toBinaryString(Math.abs(n));
            if(bits != 0 && bin.length() > bits)
                throw new NumberFormatException("overflow");
            labelOverflow.setText("Status: sem overflow!");
            while(bin.length() < bits)
                bin = '0' + bin;
            String c2 = complementa(bin);
            campoBin.setText(bin);
            campoBinC2.setText(c2);
            if(bordaAlterada){
                campoBits.setBorder(original);
                campoNumero.setBorder(original);
                bordaAlterada = false;
            }
        }catch(NumberFormatException e){
            campoBin.setText("");
            campoBinC2.setText("");
            String msg = e.getMessage();
            if(msg.equals("overflow")){
                labelOverflow.setText("Status: houve overflow!");
                campoBits.setBorder(bordaVermelha);
            }
            else{
                labelOverflow.setText("Status: erro no formato do número!");
                campoBits.setBorder(original);
                campoNumero.setBorder(bordaVermelha);
            }
            bordaAlterada = true;
        }
}//GEN-LAST:event_converter

    private void campoNumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNumeroKeyReleased
        converter(null);
    }//GEN-LAST:event_campoNumeroKeyReleased

    private void campoBitsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBitsKeyReleased
        converter(null);
    }//GEN-LAST:event_campoBitsKeyReleased

    public static int valorDecimal(String bin) throws NumberFormatException{
        int resp = 0;
        for(int i = 0; i < bin.length(); i++){
            if(bin.charAt(i) == '1')
                resp += Math.pow(2, bin.length() - i - 1);
            else if(bin.charAt(i) != '0')
                throw new NumberFormatException();
        }
        return resp;
    }
    
    private void campoBin2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBin2KeyReleased
        try{
            String bin = campoBin2.getText();
            boolean negativo = bin.startsWith("1");
            int valor = (negativo ? -1 : 1);
            if(negativo)
                bin = complementa(bin);
            valor *= valorDecimal(bin);
            campoDec2.setText(valor + "");
            labelBintoDec.setText("Status: convertido com sucesso.");
            campoBin2.setBorder(original);
        } catch(NumberFormatException e){
            campoDec2.setText("");
            labelBintoDec.setText("Status: erro na conversão.");
            campoBin2.setBorder(bordaVermelha);
        }
    }//GEN-LAST:event_campoBin2KeyReleased

    private void exibirCreditos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirCreditos
        JOptionPane.showMessageDialog(null, "Complementador a 2 e conversor binário open-source.\n\nDesenvolvido"
                + " por Mateus Azis.", "Sobre", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_exibirCreditos

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) throws Exception{
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoBin;
    private javax.swing.JTextField campoBin2;
    private javax.swing.JTextField campoBinC2;
    private javax.swing.JTextField campoBits;
    private javax.swing.JTextField campoDec2;
    private javax.swing.JTextField campoNumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel labelBintoDec;
    private javax.swing.JLabel labelOverflow;
    // End of variables declaration//GEN-END:variables

}
